config/routes.rb
Rails.application.routes.draw do
  resources :zipcodedatabases
  get 'pages/about'
  get 'pages/contact'

 root 'zipcodedatabases#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/zipcodedatabase.rb
class Zipcodedatabase < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/zipcodedatabases_controller.rb
class ZipcodedatabasesController < ApplicationController
  before_action :set_zipcodedatabase, only: [:show, :edit, :update, :destroy]

  # GET /zipcodedatabases
  # GET /zipcodedatabases.json
  def index
    @zipcodedatabases = Zipcodedatabase.all
  end

  # GET /zipcodedatabases/1
  # GET /zipcodedatabases/1.json
  def show
  end

  # GET /zipcodedatabases/new
  def new
    @zipcodedatabase = Zipcodedatabase.new
  end

  # GET /zipcodedatabases/1/edit
  def edit
  end

  # POST /zipcodedatabases
  # POST /zipcodedatabases.json
  def create
    @zipcodedatabase = Zipcodedatabase.new(zipcodedatabase_params)

    respond_to do |format|
      if @zipcodedatabase.save
        format.html { redirect_to @zipcodedatabase, notice: 'Zipcodedatabase was successfully created.' }
        format.json { render :show, status: :created, location: @zipcodedatabase }
      else
        format.html { render :new }
        format.json { render json: @zipcodedatabase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zipcodedatabases/1
  # PATCH/PUT /zipcodedatabases/1.json
  def update
    respond_to do |format|
      if @zipcodedatabase.update(zipcodedatabase_params)
        format.html { redirect_to @zipcodedatabase, notice: 'Zipcodedatabase was successfully updated.' }
        format.json { render :show, status: :ok, location: @zipcodedatabase }
      else
        format.html { render :edit }
        format.json { render json: @zipcodedatabase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zipcodedatabases/1
  # DELETE /zipcodedatabases/1.json
  def destroy
    @zipcodedatabase.destroy
    respond_to do |format|
      format.html { redirect_to zipcodedatabases_url, notice: 'Zipcodedatabase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zipcodedatabase
      @zipcodedatabase = Zipcodedatabase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zipcodedatabase_params
      params.require(:zipcodedatabase).permit(:zip, :City, :state, :StateAbb, :county)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/zipcodedatabases_helper.rb
module ZipcodedatabasesHelper
end

app/views/layouts/_bootstrap.html.erb
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

app/views/layouts/_footer.html.erb
<P>copyright Lucian</P>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Zip Code Review</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/pages/about">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="/pages/contact">Contact</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zipcode</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'layouts/bootstrap' %>
  </head>

<body>
	<%= render 'layouts/navbar' %>
	<div class="container-fluid"
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to ZipCode Review!</h1>
<h2>This is one the sample applications for <a href="http://www.baserails.com">Baserails</a>, a platform that teaches people to build awesome custome websites with the Ruby on Rails programming language.

Start leaving reviews today!!!!</h2>

app/views/pages/contact.html.erb
<h1>We would love to hear from you!</h1>
<p>Contact us at xxx@xxx.com</p>

app/views/zipcodedatabases/_form.html.erb
<%= form_with(model: zipcodedatabase, local: true) do |form| %>
  <% if zipcodedatabase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zipcodedatabase.errors.count, "error") %> prohibited this zipcodedatabase from being saved:</h2>

      <ul>
      <% zipcodedatabase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :zip %>
    <%= form.text_field :zip, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :City %>
    <%= form.text_field :City, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :state %>
    <%= form.text_field :state, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :StateAbb %>
    <%= form.text_field :StateAbb, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :county %>
    <%= form.text_field :county, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/zipcodedatabases/edit.html.erb
<h1>Editing Zipcodedatabase</h1>

<%= render 'form', zipcodedatabase: @zipcodedatabase %>

<%= link_to 'Show', @zipcodedatabase, class: "btn btn-link" %> |
<%= link_to 'Back', zipcodedatabases_path, class: "btn btn-link" %>

app/views/zipcodedatabases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Zipcodedatabases</h1>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Zip</th>
      <th>City</th>
      <th>State</th>
      <th>Stateabb</th>
      <th>County</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zipcodedatabases.each do |zipcodedatabase| %>
      <tr>
        <td><%= zipcodedatabase.zip %></td>
        <td><%= zipcodedatabase.City %></td>
        <td><%= zipcodedatabase.state %></td>
        <td><%= zipcodedatabase.StateAbb %></td>
        <td><%= zipcodedatabase.county %></td>
        <td><%= link_to 'Show', zipcodedatabase, class: "btn btn-link" %></td>
        <td><%= link_to 'Edit', edit_zipcodedatabase_path(zipcodedatabase), class: "btn btn-link" %></td>
        <td><%= link_to 'Destroy', zipcodedatabase, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zipcodedatabase', new_zipcodedatabase_path %>

app/views/zipcodedatabases/new.html.erb
<h1>New Zipcodedatabase</h1>

<%= render 'form', zipcodedatabase: @zipcodedatabase %>

<%= link_to 'Back', zipcodedatabases_path, class: "btn btn-link" %>

app/views/zipcodedatabases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Zip:</strong>
  <%= @zipcodedatabase.zip %>
</p>

<p>
  <strong>City:</strong>
  <%= @zipcodedatabase.City %>
</p>

<p>
  <strong>State:</strong>
  <%= @zipcodedatabase.state %>
</p>

<p>
  <strong>Stateabb:</strong>
  <%= @zipcodedatabase.StateAbb %>
</p>

<p>
  <strong>County:</strong>
  <%= @zipcodedatabase.county %>
</p>

<%= link_to 'Edit', edit_zipcodedatabase_path(@zipcodedatabase), class: "btn btn-link" %> |
<%= link_to 'Back', zipcodedatabases_path, class: "btn btn-link" %>